### ISSUE TITLE
Question about Fig9

### ISSUE THREAD

**Issue by Polly-LYP** [ThuCCSLab/FigStep#10]
Hello! Thanks for your great work. And I'm curious about Figure9 in your paper. What's the embedding for FigStep? Is it the output of vision encoder or projector?

**Comment by ThuCCSLab** [comment]
Hi!

Thanks for your interest in our work.
Please find the code to generate such semantic embeddings from the issue https://github.com/ThuCCSLab/FigStep/issues/6.
