### ISSUE TITLE
Dataset For jailbreaking

### ISSUE THREAD

**Issue by LiqiangJing** [ThuCCSLab/FigStep#3]
Hi, I want to use your jailbreaking datasets, could you provide them?

**Comment by YichenBC** [comment]
[screenshots.zip](https://github.com/ThuCCSLab/FigStep/files/13667749/screenshots.zip)
[forbidQI_final.csv](https://github.com/ThuCCSLab/FigStep/files/13667775/forbidQI_final.csv)

**Comment by rain305f** [comment]
Thanks a lot!
